### ISSUE TITLE
Implement CRON Jobs on all projects

### ISSUE THREAD

**Issue by itsmaica** [RubenRamirez12/Capstone-Project#23]
@RubenRamirez12 [See this Mod 7 Resource for adding CRON jobs](https://github.com/crespohector/welcome-to-mod-7#how-to-keep-your-website-alive-this-will-require-scheduled-get-requests). You will want to apply them to all projects. :D

**Comment by RubenRamirez12** [comment]
finished adding cron jobs to all projects
